### ISSUE TITLE
Include minified => exclude originals

### ISSUE THREAD

**Issue by wspringer** [ksmithut/metalsmith-uglify#8]
Would it be possible to have an option to remove the originals from the `file` object once those files were minified?

**Comment by ksmithut** [comment]
Seems like it would be easy enough. I'll work on that sometime tonight. I'll keep you posted.

**Comment by ksmithut** [comment]
@wspringer It's been a while since I've looked at my code. It's aching for a refactor and cleanup. I'm using an old version of uglify, and the tests are breaking with the new one. I'll keep this issue open, but I'm going to work on refactoring the code. I plan to have an updated version out sometime next week.

**Comment by ksmithut** [comment]
@wspringer I did a refactor, but it had a lot of breaking changes.

I initially wrote this trying to support all sorts of options and things, and wasn't allowing that functionality to exist on other plugins. I like gulp's philosophy that a plugin should do one simple thing, and let other plugins do other things.

That being said, if there is functionality that you would like included in the future, feel free to submit an issue or a PR.

For this issue, you can now do the following:

```javascript
Metalsmith(dir)
  .use(uglify({
    removeOriginal: true
  })
  .build();
```
